# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: 上传 Python 包

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-build:
    name: 构建发布分发包
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 安装 build 并打包
        run: |
          # 注意：在此处放置自己的分发构建步骤。
          python -m pip install build
          python -m build

      - name: 上传分发包
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: 发布到 PyPI
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # 重要：此权限对于受信任的发布是必需的
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/xmpy_sqlite

    steps:
      - name: 获取发布分发包
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: 将发布分发包发布到 PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
